---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: secret-mysql
  namespace: database
spec:
  encryptedData:
    password: AgB77uAVzcSjjLjrwdK0P6DDdp8rJAsd7s9yfGoH7VOzZwEPr+Gs5uFn5ldeLhsoBl4NXb8p2Dc01yTeyVJhWsUfl7yv7hOAKeB3nbDehb+D5NWKWSkgrwGjknAapKvDz4iis/neWNb3eOIC4CdwaOz6ty5k/TDVeJ8E/yuffyng1Wl0IgMx5RnyarNKUSer0vU7xKPn6cjEKL/iPWxsGfokia2XQaiuxqZWJIF8DuclnA4EkisIbivGdk78m8pfI+BqKxGQBYrI7bYWgSNSAurx2WWxv9DbnPe+btmYtFNtdJsOwYTBDqYP6e8ioFDjOGuSU8IUJeZTXWmjE1URr2Nn6rE/gY0Fsica7+MvjC01Kp2DGKN7iKksBzpag2nd9sk5/J3jJWXQZPD64WUXE3SOtDH4uBAV1bWnhtPbTSjoBjlqs30R8ccR9Djc7WLCV9M5mahMg9uYn7rTK/fT/zLjFVxwPlngexZJz+vKT1qMOBxrlexMHxxmCTgppG9eoSmpfFhtFNhH+w1uCbMYvC2W33XVnxLBtUWipccA5kGPQSfD155UWwNJ7AezNvfQFNKTc2xhqIp717CzDoaxs5JdCEdO+c3OG0ndVi5B0oMsUs0PfQx7fLgRwlzrPuUg38pu7y3+41v3Bwqgx7YfyuFUhJAgnIwfQGLO7z6VWp/v7VJQA+kTCEN24lRSGXnGZ5jajwk2b0KUZxnosBBjjZdsVqcSe1cyQGX3
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: secret-mysql
      namespace: database
